service: auth-api

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  timeout: 29
  iam:
    role: arn:aws:iam::407603477016:role/LabRole
  environment:
    USERS_TABLE: ${self:service}-users-${sls:stage}
    TOKENS_TABLE: ${self:service}-tokens-${sls:stage}
    INCIDENTS_TABLE: ${self:service}-incidents-${sls:stage}
    STAGE: ${sls:stage}

package:
  individually: true
  include:
    - "_utils.py"

###########################
# Reusable config
###########################
custom:
  protected: &protected
    cors: true
    authorizer:
      type: REQUEST
      name: customAuthorizer
      identitySource: method.request.header.Authorization

functions:
  seed:
    handler: user/seed.lambda_handler

  customAuthorizer:
    handler: hasPermission.lambda_handler

  # ---- PUBLIC ENDPOINT ----
  token-create:
    handler: mytoken/create.lambda_handler
    events:
      - http:
          path: auth/token/create
          method: post
          cors: true

  # ---- PROTECTED ENDPOINTS ----
  token-delete:
    handler: mytoken/delete.lambda_handler
    events:
      - http:
          path: auth/token/delete
          method: post
          <<: *protected

  user-create:
    handler: user/create.lambda_handler
    events:
      - http:
          path: auth/user/create
          method: post
          <<: *protected

  user-get:
    handler: user/get.lambda_handler
    events:
      - http:
          path: auth/user/get
          method: post
          <<: *protected

  user-list:
    handler: user/list.lambda_handler
    events:
      - http:
          path: auth/user/list
          method: post
          <<: *protected

  user-update:
    handler: user/update.lambda_handler
    events:
      - http:
          path: auth/user/update
          method: post
          <<: *protected

  user-delete:
    handler: user/delete.lambda_handler
    events:
      - http:
          path: auth/user/delete
          method: post
          <<: *protected

  incident-create:
    handler: incidents/create.lambda_handler
    events:
      - http:
          path: incident/create
          method: post
          <<: *protected

  incident-get:
    handler: incidents/get.lambda_handler
    events:
      - http:
          path: incident/get
          method: post
          <<: *protected

  incident-list:
    handler: incidents/list.lambda_handler
    events:
      - http:
          path: incident/list
          method: post
          <<: *protected

  incident-update:
    handler: incidents/update.lambda_handler
    events:
      - http:
          path: incident/update
          method: post
          <<: *protected

  incident-delete:
    handler: incidents/delete.lambda_handler
    events:
      - http:
          path: incident/delete
          method: post
          <<: *protected

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    TokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TOKENS_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: expiresAt
          Enabled: true

    IncidentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.INCIDENTS_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseType: DEFAULT_4XX
        RestApiId: { Ref: ApiGatewayRestApi }
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"

    GatewayResponseDefault5XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseType: DEFAULT_5XX
        RestApiId: { Ref: ApiGatewayRestApi }
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"

    ApiGatewayAuthorizerRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "apigateway.amazonaws.com"
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: "InvokeAuthorizerFunction-${sls:stage}"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - lambda:InvokeAsync
                    - lambda:InvokeFunction
                  Resource:
                    Fn::GetAtt:
                      - customAuthorizer
                      - Arn
