service: auth-api

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  timeout: 29
  iam:
    role: arn:aws:iam::407603477016:role/LabRole
  environment:
    USERS_TABLE: ${self:service}-users-${sls:stage}
    TOKENS_TABLE: ${self:service}-tokens-${sls:stage}
    STAGE: ${sls:stage}

package:
  individually: true
  include:
    - "_utils.py"

functions:
  seed:
    handler: user/seed.lambda_handler

  customAuthorizer:
    handler: hasPermission.lambda_handler

  token-create:
    handler: mytoken/create.lambda_handler
    events:
      - http:
          path: auth/token/create
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  token-delete:
    handler: mytoken/delete.lambda_handler
    events:
      - http:
          path: auth/token/delete
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
          authorizer:
            name: customAuthorizer
            identitySource: method.request.header.Authorization

  user-create:
    handler: user/create.lambda_handler
    events:
      - http:
          path: auth/user/create
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
          authorizer:
            name: customAuthorizer
            identitySource: method.request.header.Authorization

  user-get:
    handler: user/get.lambda_handler
    events:
      - http:
          path: auth/user/get
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
          authorizer:
            name: customAuthorizer
            identitySource: method.request.header.Authorization

  user-list:
    handler: user/list.lambda_handler
    events:
      - http:
          path: auth/user/list
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
          authorizer:
            name: customAuthorizer
            identitySource: method.request.header.Authorization

  user-update:
    handler: user/update.lambda_handler
    events:
      - http:
          path: auth/user/update
          method: put
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
          authorizer:
            name: customAuthorizer
            identitySource: method.request.header.Authorization

  user-delete:
    handler: user/delete.lambda_handler
    events:
      - http:
          path: auth/user/delete
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
          authorizer:
            name: customAuthorizer
            identitySource: method.request.header.Authorization

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    TokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TOKENS_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: expiresAt
          Enabled: true

    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
